from __future__ import annotations

from pathlib import Path
from typing import Any

from .mission_assurance import sha256_text, utc_now

PRODUCTION_STATUS_SCRIPT = "omega-production-status"
PRODUCTION_ATTACH_SCRIPT = "omega-attach"
PRODUCTION_PREFLIGHT_SCRIPT = "omega-preflight"


SCRIPT_MODE = 0o755


def _script_hash(content: str) -> str:
    return sha256_text(content)


def _script_header(purpose: str) -> list[str]:
    return [
        "#!/bin/sh",
        "set -eu",
        f"# {purpose}",
        "# Generated by omega_frontier.ops_scripts. Keep this guard before any raw status or attach path.",
        "OMEGA_PYTHON=\"${OMEGA_PYTHON:-python3}\"",
        "OMEGA_MINIMUM_ELIGIBLE=\"${OMEGA_MINIMUM_ELIGIBLE:-2}\"",
    ]


def _require_common_env() -> list[str]:
    return [
        ': "${OMEGA_CONTROL_DIR:?OMEGA_CONTROL_DIR is required}"',
        ': "${OMEGA_STATE_DIR:?OMEGA_STATE_DIR is required}"',
    ]


def _guarded_cli_argv_lines(command: str) -> list[str]:
    return [
        'set -- "$OMEGA_PYTHON" -m omega_frontier.cli ' + command,
        'set -- "$@" --control-dir "$OMEGA_CONTROL_DIR"',
        'set -- "$@" --state-dir "$OMEGA_STATE_DIR"',
        'set -- "$@" --minimum-eligible "$OMEGA_MINIMUM_ELIGIBLE"',
        'if [ "${OMEGA_BASE_URL:-}" != "" ]; then',
        '  set -- "$@" --base-url "$OMEGA_BASE_URL"',
        'fi',
        'if [ "${OMEGA_ROOT_HTML_FILE:-}" != "" ]; then',
        '  set -- "$@" --html-file "$OMEGA_ROOT_HTML_FILE"',
        'fi',
    ]


def render_production_status_script() -> str:
    """Render the repository-owned guarded status command.

    The script delegates to the production status guard and inherits its refusal
    semantics. It never tails or trusts a campaign log directly.
    """

    lines = [
        *_script_header("Omega guarded production status."),
        *_require_common_env(),
        *_guarded_cli_argv_lines("production-status"),
        'exec "$@"',
        "",
    ]
    return "\n".join(lines)


def render_production_attach_script() -> str:
    """Render the repository-owned guarded attach command.

    The attach guard must return a structured safe_tail_argv before this script
    execs tail. A refused guard exits with the guard's code and never reaches
    the tail path.
    """

    lines = [
        *_script_header("Omega guarded production attach."),
        *_require_common_env(),
        *_guarded_cli_argv_lines("attach"),
        "set +e",
        'OMEGA_ATTACH_GUARD_JSON=$("$@")',
        "OMEGA_ATTACH_GUARD_RC=$?",
        "set -e",
        'printf "%s\\n" "$OMEGA_ATTACH_GUARD_JSON"',
        'if [ "$OMEGA_ATTACH_GUARD_RC" -ne 0 ]; then',
        '  exit "$OMEGA_ATTACH_GUARD_RC"',
        "fi",
        'OMEGA_ATTACH_GUARD_JSON="$OMEGA_ATTACH_GUARD_JSON" exec "$OMEGA_PYTHON" -c '\''import json, os, sys; data=json.loads(os.environ.get("OMEGA_ATTACH_GUARD_JSON", "{}")); argv=data.get("safe_tail_argv"); sys.exit(5) if not argv else os.execvp(argv[0], argv)'\''',
        "",
    ]
    return "\n".join(lines)


def render_production_preflight_script() -> str:
    """Render the repository-owned preflight command.

    Preflight requires fresh HTML evidence. It is intended for launch scripts
    that fetch or materialize the root HTML before starting long-running work.
    """

    lines = [
        *_script_header("Omega guarded production preflight."),
        *_require_common_env(),
        ': "${OMEGA_BASE_URL:?OMEGA_BASE_URL is required}"',
        ': "${OMEGA_ROOT_HTML_FILE:?OMEGA_ROOT_HTML_FILE is required}"',
        'set -- "$OMEGA_PYTHON" -m omega_frontier.cli preflight',
        'set -- "$@" --control-dir "$OMEGA_CONTROL_DIR"',
        'set -- "$@" --state-dir "$OMEGA_STATE_DIR"',
        'set -- "$@" --base-url "$OMEGA_BASE_URL"',
        'set -- "$@" --html-file "$OMEGA_ROOT_HTML_FILE"',
        'set -- "$@" --minimum-eligible "$OMEGA_MINIMUM_ELIGIBLE"',
        'exec "$@"',
        "",
    ]
    return "\n".join(lines)


def repository_guard_scripts() -> dict[str, str]:
    return {
        PRODUCTION_STATUS_SCRIPT: render_production_status_script(),
        PRODUCTION_ATTACH_SCRIPT: render_production_attach_script(),
        PRODUCTION_PREFLIGHT_SCRIPT: render_production_preflight_script(),
    }


def repository_guard_manifest(script_dir: str | Path = "scripts") -> dict[str, Any]:
    """Return the repository-owned production guard script manifest."""

    root = Path(script_dir)
    scripts = repository_guard_scripts()
    entries = []
    for name, content in scripts.items():
        entries.append(
            {
                "name": name,
                "path": str(root / name),
                "sha256": _script_hash(content),
                "mode": oct(SCRIPT_MODE),
                "purpose": {
                    PRODUCTION_STATUS_SCRIPT: "truthful production status with current-run and discovery gates",
                    PRODUCTION_ATTACH_SCRIPT: "safe attach that refuses stale or root-only runs before tail",
                    PRODUCTION_PREFLIGHT_SCRIPT: "launch preflight for attach and eligible discovery gates",
                }[name],
            }
        )
    return {
        "schema": "omega.production.repository_guard_scripts.v1",
        "generated_at_utc": utc_now(),
        "script_dir": str(root),
        "scripts": entries,
        "refusal_exit_code": 5,
        "environment": {
            "OMEGA_CONTROL_DIR": "directory containing current-run.json and last-run.json",
            "OMEGA_STATE_DIR": "candidate run state directory",
            "OMEGA_BASE_URL": "target origin used for discovery gate checks",
            "OMEGA_ROOT_HTML_FILE": "root HTML captured before preflight or attach",
            "OMEGA_MINIMUM_ELIGIBLE": "minimum eligible route count; default 2",
            "OMEGA_PYTHON": "python executable; default python3",
        },
        "safe_apply": [
            "install these scripts before legacy raw tail/status scripts on PATH",
            "set OMEGA_CONTROL_DIR and OMEGA_STATE_DIR explicitly in service units or shell wrappers",
            "use omega-preflight before long-running launch and omega-attach instead of tail -F",
        ],
    }


def write_repository_guard_scripts(output_dir: str | Path) -> dict[str, Any]:
    """Write guarded scripts to a directory and make them executable."""

    root = Path(output_dir)
    root.mkdir(parents=True, exist_ok=True)
    written = []
    for name, content in repository_guard_scripts().items():
        path = root / name
        path.write_text(content, encoding="utf-8")
        path.chmod(SCRIPT_MODE)
        written.append(
            {
                "name": name,
                "path": str(path),
                "sha256": _script_hash(content),
                "mode": oct(path.stat().st_mode & 0o777),
            }
        )
    return {
        "schema": "omega.production.repository_guard_install.v1",
        "installed_at_utc": utc_now(),
        "output_dir": str(root),
        "scripts": written,
        "manifest": repository_guard_manifest(root),
    }
